package commons

var FieldNames = map[string][]string{
	"MSH": {
		"MSH Record",
		"Field Separator",
		"Encoding Characters",
		"Sending Application",
		"Sending Facility",
		"Receiving Application",
		"Receiving Facility",
		"Date/Time of Message",
		"Security",
		"Message Type",
		"Message Control ID",
		"Processing ID",
		"Version ID",
		"Sequence Number",
		"Continuation Provider",
		"Accept Acknowledgement Type",
		"Application Acknowledgement Type",
		"Country Code",
		"Character Set",
		"Principal Language of Message",
		"Alternate Character Set Handling Scheme",
		"Message Profile Identifier",
		"Sending Responsible Organization",
		"Receiving Responsible Organization",
		"Sending Network Address",
		"Receiving Network Address",
	},
	"EVN": {
		"EVN Record",
		"Event Type Code",
		"Recorded Date/Time",
		"Date/Time Planned Event",
		"Event Reason Code",
		"Operator ID",
		"Event Occurred",
		"Event Facility",
	},
	"SCH": {
		"SCH Record",
		"Placer Appointment ID",
		"Filler Appointment ID",
		"Occurrence Number",
		"Placer Group Number",
		"Schedule ID",
		"Event Reason",
		"Appointment Reason",
		"Appointment Type",
		"Appointment Duration",
		"Appointment Duration Units",
		"Appointment Timing Quantity",
		"Placer Contact Person",
		"Placer Contact Phone Number",
		"Placer Contact Address",
		"Filler Contact Person",
		"Filler Contact Phone Number",
		"Filler Contact Address",
		"Filler Contact Location",
		"Entered By Person",
		"Entered By Phone Number",
		"Entered By Location",
		"Parent Placer Appointment ID",
		"Parent Filler Appointment ID",
		"Filler Status Code",
		"Placer Order Number",
		"Filler Order Number",
	},
	"TQ1": {
		"TQ1 Record",
		"Set ID",
		"Quantity",
		"Repeat Pattern",
		"Explicit Time",
		"Relative Time and Units",
		"Service Duration",
		"Start Date/Time",
		"End Date/Time",
		"Priority",
		"Condition Text",
		"Text Instruction",
		"Conjunction",
		"Occurrence Duration",
		"Total Occurrences",
	},
	"NTE": {
		"NTE Record",
		"Set ID",
		"Source of Comment",
		"Comment",
		"Comment Type",
		"Entered By",
		"Entered Date/Time",
		"Effective Start Date",
		"Expiration Date",
	},
	"PID": {
		"PID Record",
		"Set ID",
		"Patient ID",
		"Patient Identifier List",
		"Alternate Patient ID",
		"Patient Name",
		"Mother's Maiden Name",
		"Date/Time of Birth",
		"Administrative Sex",
		"Patient Alias",
		"Race",
		"Patient Address",
		"County Code",
		"Phone Number - Home",
		"Phone Number - Business",
		"Primary Language",
		"Marital Status",
		"Religion",
		"Patient Account Number",
		"SSN Number",
		"Driver's License Number",
		"Mother's Identifier",
		"Ethnic Group",
		"Birth Place",
		"Multiple Birth Indicator",
		"Birth Order",
		"Citizenship",
		"Veteran's Military Status",
		"Nationality",
		"Patient Death Date and Time",
		"Patient Death Indicator",
		"Identity Unknown Indicator",
		"Identity Reliability Code",
		"Last Update Date/Time",
		"Last Update Facility",
		"Species Code",
		"Breed Code",
		"Strain",
		"Production Class Code",
		"Tribal Citizenship",
		"Patient Telecommunication Information",
	},
	"PD1": {
		"PD1 Record",
		"Living Dependency",
		"Living Arrangement",
		"Patient Primary Facility",
		"Patient Primary Care Provider Name and ID Number",
		"Student Indicator",
		"Handicap",
		"Living Will Code",
		"Organ Donor Code",
		"Seperate Bill",
		"Duplicate Patient",
		"Publicity Code",
		"Protection Indicator",
		"Protection Indicator Effective Date",
		"Place of Worship",
		"Advance Directive Code",
		"Immunization Registry Status",
		"Immunization Registry Status Effective Date",
		"Publicity Code Effective Date",
		"Military Branch",
		"Military Rank/Grade",
		"Military Status",
		"Advance Directive Last Verified Date",
	},
	"MRG": {
		"MRG Record",
		"Prior Patient Identifier List",
		"Prior Alternate Patient ID",
		"Prior Patient Account Number",
		"Prior Patient ID",
		"Prior Visit Number",
		"Prior Alternate Visit ID",
		"Prior Patient Name",
	},
	"PV1": {
		"PV1 Record",
		"Set ID",
		"Patient Class",
		"Assigned Patient Location",
		"Admission Type",
		"Preadmit Number",
		"Prior Patient Location",
		"Attending Doctor",
		"Referring Doctor",
		"Consulting Doctor",
		"Hospital Service",
		"Temporary Location",
		"Preadmit Test Indicator",
		"Re-admission Indicator",
		"Admit Source",
		"Ambulatory Status",
		"VIP Indicator",
		"Admitting Doctor",
		"Patient Type",
		"Visit Number",
		"Financial Class",
		"Charge Price Indicator",
		"Courtesy Code",
		"Credit Rating",
		"Contract Code",
		"Contract Effective Date",
		"Contract Amount",
		"Contract Period",
		"Interest Code",
		"Transfer to Bad Debt Code",
		"Transfer to Bad Debt Date",
		"Bad Debt Agency Code",
		"Bad Debt Transfer Amount",
		"Bad Debt Recovery Amount",
		"Delete Account Indicator",
		"Delete Account Date",
		"Discharge Disposition",
		"Discharged to Location",
		"Diet Type",
		"Servicing Facility",
		"Bed Status",
		"Account Status",
		"Pending Location",
		"Prior Temporary Location",
		"Admit Date/Time",
		"Discharge Date/Time",
		"Current Patient Balance",
		"Total Charges",
		"Total Adjustments",
		"Total Payments",
		"Alternate Visit ID",
		"Visit Indicator",
		"Other Healthcare Provider",
		"Service Episode Description",
		"Service Episode Identifier",
	},
	"DG1": {
		"DG1 Record",
		"Set ID",
		"Diagnosis Codeing Method",
		"Diagnosis Code",
		"Diagnosis Description",
		"Diagnosis Date/Time",
		"Diagnosis Type",
		"Major Diagnostic Category",
		"Diagnostic Related Group",
		"DRG Approval Indicator",
		"DRG Grouper Review Code",
		"Outlier Type",
		"Outlier Days",
		"Outlier Cost",
		"Grouper Version and Type",
		"Diagnosis Priority",
		"Diagnosing Clinician",
		"Diagnosis Classification",
		"Confidential Indicator",
		"Attestation Date/Time",
		"Diagnosis Identifier",
		"Diagnosis Action Code",
		"Parent Diagnosis",
		"DRG CCL Value Code",
		"DRG Grouping Usage",
		"DRG Diagnosis Determination Status",
		"Present On Admission Indicator",
	},
	"IN1": {
		"IN1 Record",
		"Set ID",
		"Insurance Plan ID",
		"Insurance Company ID",
		"Insurance Company Name",
		"Insurance Company Address",
		"Insurance Company Phone Number",
		"Group Number",
		"Group Name",
		"Insured's Group Emp ID",
		"Insured's Group Emp Name",
		"Plan Effective Date",
		"Plan Expiration Date",
		"Authorization Information",
		"Plan Type",
		"Name of Insured",
		"Insured's Relationship to Patient",
		"Insured's Date of Birth",
		"Insured's Address",
		"Assignment of Benefits",
		"Coordination of Benefits",
		"Coordination of Benefits Priority",
		"Notice of Admission Flag",
		"Notice of Admission Date",
		"Report of Eligibility Flag",
		"Report of Eligibility Date",
		"Release Information Code",
		"Pre-Admit Certification",
		"Verification Date/Time",
		"Verification By",
		"Type of Agreement Code",
		"Billing Status",
		"Lifetime Reserve Days",
		"Delay Before Lifetime Reserve Days",
		"Company Plan Code",
		"Policy Number",
		"Policy Deductible",
		"Policy Limit - Amount",
		"Policy Limit - Days",
		"Room Rate - Semi-Private",
		"Room Rate - Private",
		"Insured's Employment Status",
		"Insured's Administrative Sex",
		"Insured's Employer's Address",
		"Verification Status",
		"Prior Insurance Plan ID",
		"Coverage Type",
		"Handicap",
		"Insured's ID Number",
		"Signature Code",
		"Signature Code Date",
		"Insured's Birth Place",
		"VIP Indicator",
		"External Health Plan Identifier",
		"Insurance Action Code",
	},
	"IN2": {
		"IN2 Record",
		"Insured's Employee ID",
		"Insured's Social Security Number",
		"Insured's Employer's Name and ID",
		"Employer Information Data",
		"Mail Claim Party",
		"Medicare Health Insurance Card Number",
		"Medicaid Case Name",
		"Medicaid Case Number",
		"Military Sponsor Name",
		"Military ID Number",
		"Military Organization",
		"Military Station",
		"Military Service",
		"Military Rank/Grade",
		"Military Status",
		"Military Retire Date",
		"Military Non-Availibility Certificate On File",
		"Baby Coverage",
		"Combine Baby Bill",
		"Blood Deductible",
		"Special Coverage Approval Name",
		"Special Coverage Approval Title",
		"Non-Covered Insurance Code",
		"Payor ID",
		"Payor Subscriber ID",
		"Eligibility Source",
		"Room Coverage Type/Amount",
		"Policy Type/Amount",
		"Daily Deductible",
		"Living Dependency",
		"Ambulatory Status",
		"Citizenship",
		"Primary Language",
		"Living Arrangement",
		"Publicity Code",
		"Protection Indicator",
		"Student Indicator",
		"Religion",
		"Mother's Maiden Name",
		"Nationality",
		"Ethnic Group",
		"Marital Status",
		"Insured's Employment Start Date",
		"Employment Stop Date",
		"Job Title",
		"Job Code/Class",
		"Job Status",
		"Employer Contact Person's Name",
		"Employer Contact Person's Phone Number",
		"Employer Contact Reason",
		"Insured's Contact Person's Name",
		"Insured's Contact Person's Phone Number",
		"Insured's Contact Person's Reason",
		"Relationship to the Patient Start Date",
		"Relationship to the Patient Stop Date",
		"Insurance Co. Contact Reason",
		"Insurance Co. Contact Phone Number",
		"Policy Scope",
		"Policy Source",
		"Patient Member Number",
		"Guarantor's Relationship to Insured",
		"Insured's Phone Number - Home",
		"Insured's Employer Phone Number",
		"Military Handicapped Program",
		"Suspended Flag",
		"Copay Limit Flag",
		"Stop Loss Limit Flag",
		"Insured Organization Name and ID",
		"insured Employer Organization Name and ID",
		"Race",
		"Patient Relationship to Insured",
	},
	"NK1": {
		"NK1 Record",
		"Set ID",
		"Name",
		"Relationship",
		"Address",
		"Phone Number",
		"Business Phone Number",
		"Contact Role",
		"Start Date",
		"End Date",
		"Next of Kin/Associated Parties Job Title",
		"Next of Kin/Associated Parties Job Code/Class",
		"Next of Kin/Associated Parties Employee Number",
		"Organization Name",
		"Marital Status",
		"Administrative Sex",
		"Date/Time of Birth",
		"Living Dependency",
		"Ambulatory Status",
		"Citizenship",
		"Primary Language",
		"Living Arrangement",
		"Publicity Code",
		"Protection Indicator",
		"Student Indicator",
		"Religion",
		"Mother's Maiden Name",
		"Nationality",
		"Ethnic Group",
		"Contact Reason",
		"Contact Person's Name",
		"Contact Person's Telephone Number",
		"Contact Person's Address",
		"Next of Kin/Associated Parties Identifiers",
		"Job Status",
		"Race",
		"Handicap",
		"Contact Person's Social Security Number",
		"Next of Kin/Associated Parties Birth Place",
		"VIP Indicator",
		"Next of Kin/Associated Parties Telecommunication Information",
		"Contact Person's Telecommunication Information",
	},
	"AIS": {
		"AIS Record",
		"Set ID",
		"Segment Action Code",
		"Universal Service Identifier",
		"Start Date/Time",
		"Start Date/Time Offset",
		"Start Date/Time Offset Units",
		"Duration",
		"Duration Units",
		"Allow Substitution Code",
		"Filler Status Code",
		"Placer Suppliment Service Information",
		"Filler Suppliment Service Information",
	},
	"AIG": {
		"AIG Record",
		"Set ID",
		"Segment Action Code",
		"Resource ID",
		"Resource Type",
		"Resource Group",
		"Resource Quantity",
		"Resource Quantity Units",
		"Start Date/Time",
		"Start Date/Time Offset",
		"Start Date/Time Offset Units",
		"Duration",
		"Duration Units",
		"Allow Substitution Code",
		"Filler Status Code",
	},
	"AIL": {
		"AIL Record",
		"Set ID",
		"Segment Action Code",
		"Location Resource ID",
		"Location Type",
		"Location Group",
		"Start Date/Time",
		"Start Date/Time Offset",
		"Start Date/Time Offset Units",
		"Duration",
		"Duration Units",
		"Allow Substitution Code",
		"Filler Status Code",
	},
	"AIP": {
		"AIP Record",
		"Set ID",
		"Segment Action Code",
		"Perssonel Resource ID",
		"Resource Type",
		"Resource Group",
		"Start Date/Time",
		"Start Date/Time Offset",
		"Start Date/Time Offset Units",
		"Duration",
		"Duration Units",
		"Allow Substitution Code",
		"Filler Status Code",
	},
	"ORC": {
		"ORC Record",
		"Order Control",
		"Placer Order Number",
		"Filler Order Number",
		"Placer Group Number",
		"Order Status",
		"Response Flag",
		"Quantity/Timing",
		"Parent",
		"Date/Time of Transaction",
		"Entered By",
		"Verified By",
		"Medications Prescribing Provider",
		"Enterer's Location",
		"Call Back Phone Number",
		"Order Effective Date/Time",
		"Order Control Code Reason",
		"Entering Organization",
		"Entering Device",
		"Action by",
		"Advanced Beneficiary Notice Code",
		"Ordering Facility Name",
		"Ordering Facility Address",
		"Ordering Facility Phone Number",
		"Ordering Provider Address",
	},
	"RXE": {
		"RXE Record",
		"Quantity/Timing",
		"Give Code",
		"Give Amount - Minimum",
		"Give Amount - Maximum",
		"Give Units",
		"Give Dosage Form",
		"Provider's Administration  Instructions",
		"Deliver-to Location",
		"Substitution Status",
		"Dispense Amount",
		"Dispense Units",
		"Number of Refills",
		"Order Provider's DEA Number",
		"Pharmacist/Treatment Supplier's",
		"Prescription Number",
		"Number of Refills Remaining",
		"Number of Refills/Doses Dispensed",
		"Date/Time of Most Recent Refill or Dose Dispensed",
		"Total Daily Doses",
		"Needs Human Review",
		"Pharmacy/Treatment Supplier's Special Dispensing Instructions",
		"Give Per",
		"Give Rate Amount",
		"Give Rate Units",
		"Give Strength",
		"Give Strength Units",
		"Give Indicatoin",
		"Dispense Package Size",
		"Dispense Package Size Unit",
		"Dispense Package Method",
		"Supplementary Code",
		"Date/Time of Transaction",
		"Give Drug Strength Volume",
		"Give Drug Strength Volume Units",
		"Controlled Substance Schedule",
		"Formulary Status",
		"Pharmaceutical Substance  Alternative",
		"Pharmacy of Most Recent Fill",
		"Initial Dispense Amount",
		"Dispensing Pharmacy",
	},
	"RXR": {
		"RXR Record",
		"Route",
		"Site",
		"Administration Device",
		"Administration method",
		"Routing Instructions",
	},
	"ZWA": {
		"ZWA Record",
		"unused",
		"First Filled Date",
		"Last Filled Date",
		"Date Written",
		"Expiration Date",
		"Day Supply",
		"Second Sig",
		"unused",
		"unused",
		"Dispense Quantity Remaining",
		"Dispense Quantity Remaining Unit",
		"Origin Code",
		"Legacy Pharmacy Name",
		"Legacy Pharmacy DEA Number",
		"unused",
		"Prescription Serial Number",
	},
}
